In [46]:
import pandas as pd
import numpy as np

In [47]:
df = pd.read_csv("spam (1).csv", encoding='latin-1')

In [48]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [49]:
df["Category"] = np.where(df["Category"] == "ham", 0, 1)

In [50]:
df.head()

Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

In [51]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [52]:
stemming = PorterStemmer()
corpus = []

for i in range (0,len(df)):
 s1 = re.sub('[^a-zA-Z]',repl = ' ',string = df['Message'][i])
 s1.lower()
 s1 = s1.split()
 s1 = [stemming.stem(word) for word in s1 if word not in set(stopwords.words('english'))]
 s1 = ' '.join(s1)
 corpus.append(s1)

corpus[50]

'what think first time saw class'

In [53]:
from sklearn.feature_extraction.text import CountVectorizer
countvectorizer =CountVectorizer()

In [54]:
x = countvectorizer.fit_transform(corpus).toarray()

In [55]:
print(x)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [56]:
y = df['Category'].values
print(y)

[0 0 1 ... 0 0 0]


In [57]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3, stratify=y,random_state=100)

In [58]:
from sklearn.naive_bayes import MultinomialNB
multinomialnb = MultinomialNB()
multinomialnb.fit(x_train,y_train)

MultinomialNB()

In [59]:
y_pred = multinomialnb.predict(x_test)

In [60]:
acc_nb =multinomialnb.score(x_test, y_test)*100

In [61]:
acc_nb

97.60765550239235

In [69]:
result = multinomialnb.predict(countvectorizer.transform([''' Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's''']))
print(result)
if result==0:
    print("This is a Ham message")
else:
    print("This is a Spam Message")

[1]
This is a Spam Message


In [63]:
result = multinomialnb.predict(countvectorizer.transform([''' Even my brother is not like to speak with me. They treat me like aids patent.''']))
print(result)
if result==0:
    print("This is a Ham message")
else:
    print("This is a Spam Message")


[0]
This is a Ham message


In [64]:
from sklearn.svm import LinearSVC
linearsvc = LinearSVC()
linearsvc.fit(x_train,y_train)

LinearSVC()

In [65]:
y_pred = linearsvc.predict(x_test)

In [66]:
acc_svc =linearsvc.score(x_test, y_test)*100
acc_svc

98.26555023923444

In [67]:
result = linearsvc.predict(countvectorizer.transform([''' Your free ringtone is waiting to be collected. Simply text the password "MIX" to 85069 to verify. Get Usher and Britney. FML, PO Box 5249, MK17 92H. 450Ppw 16''']))
print(result)
if result==0:
    print("This is a Ham message")
else:
    print("This is a Spam Message")

[1]
This is a Spam Message


In [68]:
result = linearsvc.predict(countvectorizer.transform(['''Sorry to be a pain. Is it ok if we meet another night? I spent late afternoon in casualty and that means i haven't done any of y stuff42moro and that includes all my time sheets and that. Sorry.''']))
print(result)
if result==0:
    print("This is a Ham Message")
else:
    print("This is a Spam Message")

[0]
This is a Ham Message
